In [1]:
import numpy as np

In [56]:
def householder_qr(A):
    ''' Add some comments
    '''
    rows, cols = A.shape

    for k in range(min(cols, rows-1)):
        print('\n')
        print(A[k:,k])
        alpha_k = -np.sign(A[k,k]) * np.linalg.norm(A[k:,k], 2)
        t = np.array([0 for _ in range(rows - len(A[k:,k]))] + list(A[k:,k]))
        e_k = np.array([0 for _ in range(rows - len(A[k:,k]))] + [1] + [0 for _ in range(k,rows-1)])

        print(alpha_k, t, e_k)

        v_k =  t.T - alpha_k * e_k

        print(v_k)
        
        beta_k = np.dot(v_k.T, v_k)

        print(beta_k)

        if beta_k == 0:
            break

        for j in range(k, cols):
            print(A)
            gamma_j = v_k.T @ A[:,j]
            t = (2 * gamma_j / beta_k) * v_k
            print(t)
            A[:,j] = A[:,j] - t
        
        # print(A)
    
    return A


A = np.array([[1,2,3],[2,4,1],[5,7,1]], dtype=float)
householder_qr(A)




[1. 2. 5.]
-5.477225575051661 [1. 2. 5.] [1 0 0]
[6.47722558 2.         5.        ]
70.95445115010332
[[1. 2. 3.]
 [2. 4. 1.]
 [5. 7. 1.]]
[6.47722558 2.         5.        ]
[[-5.47722558  2.          3.        ]
 [ 0.          4.          1.        ]
 [ 0.          7.          1.        ]]
[10.21583836  3.15438709  7.88596772]
[[-5.47722558 -8.21583836  3.        ]
 [ 0.          0.84561291  1.        ]
 [ 0.         -0.88596772  1.        ]]
[4.82574186 1.49006447 3.72516118]


[ 0.84561291 -0.88596772]
-1.224744871391589 [ 0.          0.84561291 -0.88596772] [0 1 0]
[ 0.          2.07035778 -0.88596772]
5.071320152361951
[[-5.47722558 -8.21583836 -1.82574186]
 [ 0.          0.84561291 -0.49006447]
 [ 0.         -0.88596772 -2.72516118]]
[ 0.          2.07035778 -0.88596772]
[[-5.47722558 -8.21583836 -1.82574186]
 [ 0.         -1.22474487 -0.49006447]
 [ 0.          0.         -2.72516118]]
[ 0.          1.14292869 -0.48909321]


array([[-5.47722558, -8.21583836, -1.82574186],
       [ 0.        , -1.22474487, -1.63299316],
       [ 0.        ,  0.        , -2.23606798]])

In [57]:
A = np.array([[1,2,3],[2,4,1],[5,7,1]])
np.linalg.qr(A)[1]

array([[-5.47722558, -8.21583836, -1.82574186],
       [ 0.        , -1.22474487, -1.63299316],
       [ 0.        ,  0.        , -2.23606798]])