# Homework set 2

Please **submit this Jupyter notebook through Canvas** no later than **Mon Nov. 14, 9:00**. **Submit the notebook file with your answers (as .ipynb file) and a pdf printout. The pdf version can be used by the teachers to provide feedback. A pdf version can be made using the save and export option in the Jupyter Lab file menu.**

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

# Exercise 0
Write down the names + student ID of the people in your group.

Marcel van de Lagemaat - 10886699 <br>
Anton Andersen - 14718758

Run the following cell to import some packages, add additional packages yourself when needed.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Exercise 1

## (a) 1 point
Let $A$ be the matrix $\begin{bmatrix} 1 & -1 & \alpha \\ 2 & 2 & 1 \\ 0 & \alpha & -3/2 \end{bmatrix}$. For which values of $\alpha$ is $A$ singular?

By using the condition that the determinant should be zero if the matrix is singular, the values for which this holds true are solved for.
By calculating the determinant using the matrix:
$\begin{bmatrix} a_1 & b_1 & c_1 \\ a_2 & b_2 & c_2 \\ a_3 & b_3 & c_3 \end{bmatrix}$ <br>
and the formula $a_1(b_2 c_3 - b_3 c_2) - a_2(b_1 c_3 - b_3 c_1) + a_3(b_1 c_2 - b_2 c_1) = 0$
Then pluggin in the values, we solve for $\alpha = 2$ and $\alpha = -1.5$, for these values the matrix will be singular.

## (b) 1 point
For the largest value of $\alpha$ you found above, find a nonzero vector $b$ such that $Ax = b$ has infinitely many solutions. Explain your answer.

YOUR ANSWER HERE
You find an expression for b

# Exercise 2

For solving linear systems such as $Ax = b$, it is unnecessary (and often unstable) to compute the inverse $A^{-1}$. Nonetheless, there can be situations where it is useful to compute $A^{-1}$ explicitly. One way to do so is by using the LU-decomposition of $A$.

## (a) 2 points
Write an algorithm to compute $A^{-1}$ for a non-singular matrix $A$ using its LU-decomposition. You can use `scipy.linalg.lu` (which returns an LU-decomposition with _partial pivoting_, i.e., with a permutation matrix $P$) and the other `scipy.linalg.lu_*` functions, but not `scipy.linalg.inv` (or other methods for computing matrix inverses directly).

(Make sure to import the necessary functions/packages.)

In [24]:
import scipy

def invert(A):
    '''invert the matrix A'''
    # YOUR CODE HERE
    lu, piv = scipy.linalg.lu_factor(A)
    a_inv = scipy.linalg.lu_solve((lu, piv), np.eye(len(A)))
    return a_inv


A = np.array([[2, 5, 8, 7], [5, 2, 7, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
a_inv = invert(A)

print(scipy.linalg.inv(A))
print(a_inv)
print(f'The matrices are equal: {np.allclose(a_inv, scipy.linalg.inv(A))}')

[[-0.16580311  0.06217617  0.1865285  -0.05699482]
 [ 0.13471503 -0.30051813  0.0984456   0.10880829]
 [ 0.08981002  0.13298791  0.0656304  -0.26079447]
 [-0.00863558  0.04490501 -0.19861831  0.23661485]]
[[-0.16580311  0.06217617  0.1865285  -0.05699482]
 [ 0.13471503 -0.30051813  0.0984456   0.10880829]
 [ 0.08981002  0.13298791  0.0656304  -0.26079447]
 [-0.00863558  0.04490501 -0.19861831  0.23661485]]
The matrices are equal: True


## (b) 1 point
What is the computational complexity of your algorithm, given that the input matrix has size $n \times n$?
Give a short calculation/explanation for your answer.

YOUR ANSWER HERE



# Exercise 3

## (a) (2 points) 
What happens when Gaussian elimination with partial pivoting is used on a matrix of the following form?
$$
  \begin{bmatrix}
     1 &  0 &  0 &  0 &  1 \\
    -1 &  1 &  0 &  0 &  1 \\
    -1 & -1 &  1 &  0 &  1 \\
    -1 & -1 & -1 &  1 &  1 \\
    -1 & -1 & -1 & -1 &  1 
  \end{bmatrix}
$$
Do the entries of the transformed matrix grow? What happens if complete pivoting is used instead? (Note that part (a) does not require a computer.)


YOUR ANSWER HERE
Column n for the U matrix doubles every row for partial pivoting and the lower triangular becomes zero. While for full pivoting the entries in column n shift to the right side of the diagonal and the lower triangular becomes zero.
For the partial pivoting the upper triangular matrix becomes.
$$
  \begin{bmatrix}
     1 &  0 &  0 &  0 &  1 \\
     0 &  1 &  0 &  0 &  2 \\
     0 &  0 &  1 &  0 &  4 \\
     0 &  0 &  0 &  1 &  8 \\
     0 &  0 &  0 &  0 &  16 
  \end{bmatrix}
$$
For the full pivoting the upper triangular matrix becomes.
$$
  \begin{bmatrix}
     1 &  1 &  0 &  0 &  0 \\
     0 &  2 &  1 &  0 &  0 \\
     0 &  0 & -2 &  1 &  0 \\
     0 &  0 &  0 & -2 &  1 \\
     0 &  0 &  0 &  0 & -2 
  \end{bmatrix}
$$

## (b) (2 points)
Write a method that generates a matrix of the form of part (a) of size $n \times n$ for any $n$. Use a library routine for Gaussian elimination with partial pivoting to solve various sizes of linear systems of this form, using right-hand-side vectors chosen so that the solution is known. Try for example the case where the true solution is a vector of uniformly distributed random numbers between 0 and 1. How do the error, residual, and condition number behave as the systems become larger? Comment on the stability (see chapter 1) of Gaussian elimination with partial pivoting in this case.

N.B. This is an artificially contrived system that does not reflect the behavior of Gaussian elimination in realistic examples.

In [25]:
# YOUR CODE HERE
def matrix_gen(n):
    m = np.zeros([n,n])
    for row in range(n):
        for col in range(n):
            if row == col or col == n-1:
                m[row,col] = 1
            elif row > col:
                m[row,col] = -1 
    return m

n = 5
m = matrix_gen(n)
print(m)

[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]
